### ISSUE TITLE
Make tests upkeep feasible

### ISSUE THREAD

**Issue by bbfsdev** [bbfsdev/bbfs#178]
Currently we are not writing any tests and don't actually check enough.
We have to make sure:
1) No merge is merged without all static tests pass.
2) It is easy to maintain tests.
3) It is easy to create new tests.

**Comment by yarondbb** [comment]
Content data tests are fixed

**Comment by genadyp** [comment]
**TODO:**

Priority: high
- Make rake pass
  - [ ] remove obsolete tests
  - [x] fix relevant tests

Priority: medium
- to check what code should be covered with tests
  - add absent tests
  - [x] SimpleCov used to get code coverage
- to check what code should not be covered with tests
  - remove redundant tests
  - connected to #212 
- to check test correctness
  - [tcp_spec](https://github.com/bbfsdev/bbfs/blob/master/spec/networking/tcp_spec.rb) does not look to test something
- code doesn't pass code review without relevant testing ( _need team approval_ )
  - branch must be tested before merge into master
  - master must be tested after merge with another branch
  - add bullet to workflow documentation

Priority: low
- [x] re-write with rspec all tests written with minitest framework.

Nice to have
- Daily tests

**Comment by genadyp** [comment]
branch: issue178 (based on master from 2013--7-26)

**Comment by yarondbb** [comment]
the branch is old (difficult to merge with master)

Lets open a new branch from current master

**Comment by yarondbb** [comment]
Opened new branch - issue-178-test_coverage

**Comment by genadyp** [comment]
#163 will be fixed here

**Comment by genadyp** [comment]
New branch [issue178_refactor](https://github.com/bbfsdev/bbfs/tree/issue178_refactor)

**Comment by genadyp** [comment]
[Code Coverage](http://genadyp.github.io/bbfs.coverage/#_AllFiles)

#### Non-covered at all:

**Appear in the report:**
lib/content_server/backup_server.rb
lib/content_server/content_receiver.rb
lib/content_server/queue_copy.rb
lib/content_server/remote_content.rb
lib/file_monitoring/file_monitoring.rb
lib/file_monitoring/monitor_path.rb
lib/process_monitoring/monitoring_info.rb
lib/process_monitoring/send_email.rb
lib/file_monitoring.rb

**Do not appear in the report**
lib/content_server/content_server.rb
lib/email/email.rb
lib/testing_memory/testing_memory.rb
lib/testing_server/testing_server.rb

**Comment by genadyp** [comment]
New branch created [issue178_code_coverage](https://github.com/bbfsdev/bbfs/tree/issue178_code_coverage)

Committed code includes:
-  Code coverage support

```
Creates coverage report based on rspecs.
Usage:
   rake coverage
Current implementation: 
   SimpleCov package.
SimpleCov suggestions:
   * see spec/spec_helper.rb file
   * SimpleCov related code must be issued before any of your application code is required
Output:
   <project root>/coverage directory containing report files will be created.
To view report:
   open in a browser <project root>/coverage/index.html file. 
```
- move all minitest tests to RSpec format
- new_spec rake task, that creates new template spec

```
Creates new template rspec file associated with provided source file.
Parameter:
  src=<path of associated source file>
  If no parameter was provided, then user will be asked to enter a source file.
Usage:  
     rake new_spec src=<path of associated source file>
     rake new_spec
     Examples:
       rake new_spec src=lib/email/email.rb
       rake new_spec
Output:
  New template rspec file will be created.
  If absent then a suite directory will be created (see examples below).
  Example:
    * rake new_spec src=lib/email/email.rb
      Suite directory will be created: spec/email/          
      RSpec file will be created: spec/email/email_spec.rb
    * rake new_spec src=lib/file_monitoring/file_monitoring.rb   
      We already have spec/file_monitoring/ directory, so no need to create new one.
      RSpec file will be created: spec/file_monitoring/file_monitoring_spec.rb
```

Pull request #252
