### ISSUE TITLE
ContentData file utils performance issue

### ISSUE THREAD

**Issue by genadyp** [bbfsdev/bbfs#260]
**Issue description:**

> 2)  "file_utils" is able to run with "content_server" version 1.5.0
> But It works very slow. I did not get a result during 15 minutes.
> So I have terminated it. (Shirai)
#### TODO
- [x] Rake task for performance (see Rspec tag usage). `spec` task should be updated not to run performance tests. [_Rake perf and Rake all_specs are added, Rake spec run w/o performance tests_]  
- [x] Memory performance checks are too inaccurate. Consider replace/remove.
  [_Fixed: `ps` returns memory usage in KB and we assume bytes._]
- [x] GoogleHashes implementation [ #262 ]
- [ ] Update BBFS specifications, if we have any
- [ ] ContentData cloning performance improvement. [_Worth to wait for the results with GoogleHashes_]
- [ ] Ruby 2.1.1 as a project requirement

**Comment by genadyp** [comment]
Working branch: [issue260_diff_performance](https://github.com/bbfsdev/bbfs/tree/issue260_diff_performance)

**Comment by genadyp** [comment]
**Content Data Performance Test**
1. Object initialization  
   1. Init one object  
      1. 350000 instances in less then 600 seconds  
      2. clone from exist object of 350000 in less thes 600 seconds  
   2. Init more then one object  
      1. two object each of 350000 instances in less then 1200 seconds
2. File operations  
   1. save/load on 350000 instances in less then 600 seconds  
3. Set operations
   1. minus of two objects with 350000 instances each
      1. finish in less then 600 seconds

**Results:**

> ContentData init for 350000 instancesfinished in 7 seconds
> **Clone from exist object of 350000 instances finished in 382 seconds**
> Init of 2 ContentData of 350000 instances each finished in 34 seconds
> **To file for 350000 finished in 325 seconds**
> From file for 350000 finished in 34 seconds
> **ContentData minus for 350000 finished in 536 seconds**

**Problems:**
1. Clone operation
   1. minus operation depends on clone
2. To file
   1. takes x10 times then from file
3. ~~Looks like more objects we initialize - it takes more time per initialization~~  
     Init of 3 ContentData of 350000 instances each finished in 54 seconds
     while init of 2 objects finished in 34 seconds.
     Looks like there is a jump only for more then 1 object and there is no geometric progression.

**Comment by kolmanv** [comment]
1) Why minus depends on clone? This might not be necessary.
2) To file is slower because of the gzip. Try testing for time without the
Gzip. But that times might be acceptable.

**Comment by genadyp** [comment]
I am using master version without GZip
Still it is strange - i expected that from file takes more time cause then we initialize objects.

**Comment by genadyp** [comment]
Looks like a problem is not clone itself but iteration over all instances.
It takes, without any operation, just an itertion, about 330 seconds on 350_000 instances.

**Comment by genadyp** [comment]
Version without clone:

> **ContentData minus for 350000 instances finished in 348 seconds**

with clone it takes ~548 seconds

**Comment by kolmanv** [comment]
Are any other way of iteration is faster?
There are different ways to iterate over data structure.
What about Ruby 2.1.1? It might be faster.

**Comment by genadyp** [comment]
@yarondbb 
@kolmanv 
[google_hash](https://github.com/rdp/google_hash) was checked.
From the online module README:

> basically slightly slower, except for an #each method that is _much_ faster, and, as I said, RAM usage might be much better using this than the standard Ruby hash, esp. 

**Test code:**

```
puts Benchmark.measure  { @cd1.each_instance { |ch,_,_,_,_,_,_| ch } }
```

**Benchmark output format**
user CPU time, system CPU time, the sum of the user and system CPU times, and the elapsed real time

**Ruby enumerators result:**

> 852.050000   3.150000 855.200000 **(858.411330)**

**google_hash result:**

> 2.570000   0.000000   2.570000 **(  2.579969)**

To get more complete  results  need to do more changes in the code - can take a while.
But meanwhile it looks like it worth to move to the google_hash - it is **much faster**, at least for iterations.
There can be a pitfalls:
- I am using a threads in the benchmark and this module throws an exceptions while with original hashes it is all right. Need investigation.
- looks like google_hash do not support all hash methods, at least _each_key_ was unrecognized.  
  Need investigation.

**Comment by kolmanv** [comment]
Please check Ruby 2.1.1 it might be faster there. Before we move to google
hashes.

**Comment by kolmanv** [comment]
Not supported by RVM might not be a stopper. In Any case we have to check
2.1.1 and see if it is better. We don't have to use MRI Ruby ether.
This might be a different issue though.

**Comment by genadyp** [comment]
> Not supported by RVM might not be a stopper. In Any case we have to check 2.1.1 and see if it is better. We don't have to use MRI Ruby ether. This might be a different issue though.

Was already fixed - there was a need to upgrade rvm.
Same RVM issue with our test machines. On f1.test RVM was upgraded and Ruby2.1.1 installed.
Have results. Publish them later in ordered way.

**Comment by bbfsdev** [comment]
Adding parallel issue to add google hashes #262. Working on it.

**Comment by bbfsdev** [comment]
Gena please check add_google_hashes branch. I'm using "benchmark" to measure time which seems more accurate.

**Comment by bbfsdev** [comment]
Testing with google_hashes I got slower runtime results :(
Gena what did you do to get faster results?

**Comment by genadyp** [comment]
@yarondbb 
@kolmanv 

There are currently two versions of the benchmark:
Which one we are taking?
@kolmanv , inform please when you are working on the same parts of the code.
We talked that you implement google_hash (content_data.rb), but actually benchmark was changed, it means that we both worked on the same code and one version is redundant (~ 5 hours that I spent today, may going to the waste). There is a code review if something in the code looks to be improved.

**Comment by genadyp** [comment]
Looks OK with **ruby-1.9.3-p327**

> [genadyp@lnx-genadyp bbfs.google_hash]$ rvm current
> ruby-1.9.3-p327
> 
> [genadyp@lnx-genadyp bbfs.google_hash]$ git branch
> * add_google_hashes
> 
> [DEBUG] [2014-04-05 22:39:21] [content_data_performance_spec.rb:106:ContentData init for 35000 instancesfinished in 1 seconds]
> [DEBUG] [2014-04-05 22:39:21] [content_data_performance_spec.rb:20:1.252998689]
> [DEBUG] [2014-04-05 22:39:29] [content_data_performance_spec.rb:145:Clone from exist object of 35000 instances finished in 7 seconds]
> [DEBUG] [2014-04-05 22:39:29] [content_data_performance_spec.rb:20:8.091438102]
> [DEBUG] [2014-04-05 22:39:31] [content_data_performance_spec.rb:194:Init of 2 ContentData of 35000 instances each finished in 1 seconds]
> [DEBUG] [2014-04-05 22:39:31] [content_data_performance_spec.rb:20:1.208703525]
> [DEBUG] [2014-04-05 22:39:33] [content_data_performance_spec.rb:248:Init of 3 ContentData of 35000 instances each finished in 2 seconds]
> [DEBUG] [2014-04-05 22:39:33] [content_data_performance_spec.rb:20:2.100757673]
> [DEBUG] [2014-04-05 22:39:41] [content_data_performance_spec.rb:298:To file for 35000 instances finished in 8 seconds]
> [DEBUG] [2014-04-05 22:39:42] [content_data_performance_spec.rb:329:From file for 35000 instances finished in 1 seconds]
> [DEBUG] [2014-04-05 22:39:42] [content_data_performance_spec.rb:20:9.123433316]
> [DEBUG] [2014-04-05 22:39:56] [content_data_performance_spec.rb:380:ContentData minus for 35000 instances finished in 11 seconds]
> [DEBUG] [2014-04-05 22:39:56] [content_data_performance_spec.rb:20:12.520111807]

**Comment by genadyp** [comment]
With **ruby-2.1.1**

> [genadyp@lnx-genadyp bbfs.google_hash]$ rvm current
> ruby-2.1.1
> [genadyp@lnx-genadyp bbfs.google_hash]$ git branch
> * add_google_hashes
> [genadyp@lnx-genadyp bbfs.google_hash]$ rspec -fd spec/content_data/content_data_performance_spec.rb  | grep DEBUG
> [DEBUG] [2014-04-05 22:52:43] [content_data_performance_spec.rb:106:ContentData init for 35000 instancesfinished in 1 seconds]
> [DEBUG] [2014-04-05 22:52:43] [content_data_performance_spec.rb:20:0.627760693]
> [DEBUG] [2014-04-05 22:52:53] [content_data_performance_spec.rb:145:Clone from exist object of 35000 instances finished in 10 seconds]
> [DEBUG] [2014-04-05 22:52:53] [content_data_performance_spec.rb:20:10.464339437]
> [DEBUG] [2014-04-05 22:52:54] [content_data_performance_spec.rb:194:Init of 2 ContentData of 35000 instances each finished in 1 seconds]
> [DEBUG] [2014-04-05 22:52:54] [content_data_performance_spec.rb:20:1.100600526]
> [DEBUG] [2014-04-05 22:52:56] [content_data_performance_spec.rb:248:Init of 3 ContentData of 35000 instances each finished in 2 seconds]
> [DEBUG] [2014-04-05 22:52:56] [content_data_performance_spec.rb:20:2.000651712]
> [DEBUG] [2014-04-05 22:53:00] [content_data_performance_spec.rb:298:To file for 35000 instances finished in 3 seconds]
> [DEBUG] [2014-04-05 22:53:01] [content_data_performance_spec.rb:329:From file for 35000 instances finished in 1 seconds]
> [DEBUG] [2014-04-05 22:53:01] [content_data_performance_spec.rb:20:4.002311812]
> [DEBUG] [2014-04-05 22:53:04] [content_data_performance_spec.rb:380:ContentData minus for 35000 instances finished in 3 seconds]
> [DEBUG] [2014-04-05 22:53:04] [content_data_performance_spec.rb:20:3.195543031]

**Comment by genadyp** [comment]
@kolmanv 
I do not see in the [add_google_hashes](https://github.com/bbfsdev/bbfs/commit/b247ddced053d939a5d83ef7529a28af54cea7e7) branch that GoogleHash was used.
Do you use a Ruby hash with less strict conditions in the test?

**Comment by genadyp** [comment]
> [genadyp@lnx-genadyp bbfs]$ git branch
> *** issue260_diff_performance**
>   master
> [genadyp@lnx-genadyp bbfs]$ rvm current
> **ruby-1.9.3-p327**
> [genadyp@lnx-genadyp bbfs]$ rspec -fd spec/content_data/content_data_performance_spec.rb
> [DEBUG] [2014-04-05 22:55:07] [content_data_performance_spec.rb:47:Init one object 350000 instances in less then 300 seconds: finished in 9 seconds]
> [DEBUG] [2014-04-05 23:02:12] [content_data_performance_spec.rb:47:Init one object clone from exist object of 350000 in less thes 300 seconds: do not finished in 300 seconds]
> [DEBUG] [2014-04-05 23:02:37] [content_data_performance_spec.rb:47:Init more then one object two object of 350000 instances each in less then 600 seconds: finished in 20 seconds]
> [DEBUG] [2014-04-05 23:03:28] [content_data_performance_spec.rb:47:Init more then one object three object of 350000 instances each in less then 900 seconds: finished in 35 seconds]
> [DEBUG] [2014-04-05 23:09:41] [content_data_performance_spec.rb:47:Iteration each instance on 350000 instances in less then 300: finished in 285 seconds]
> [DEBUG] [2014-04-05 23:18:15] [content_data_performance_spec.rb:47:minus of two objects with 350000 instances each finish in less then 300 seconds: do not finished in 300 seconds]
> **Failures:**
>   1) Content Data Performance Test Object initialization Init one object clone from exist object of 350000 in less thes 300 seconds
>      Failure/Error: limit.elapsed_time.should < LIMIT_TIME
>        expected: < 300
>             got:   300
>   2) Content Data Performance Test Set operations minus of two objects with 350000 instances each finish in less then 300 seconds
>      Failure/Error: limit.elapsed_time.should < LIMIT_TIME
>        expected: < 300
>             got:   300

**Comment by genadyp** [comment]
> [genadyp@lnx-genadyp bbfs]$ rvm current
> **ruby-2.1.1** 
> [genadyp@lnx-genadyp bbfs]$ git branch
> ***issue260_diff_performance**
>   master
> [genadyp@lnx-genadyp bbfs]$ rspec -fd spec/content_data/content_data_performance_spec.rb
> [DEBUG] [2014-04-05 23:39:39] [content_data_performance_spec.rb:47:Init one object 350000 instances in less then 300 seconds: finished in 4 seconds]
> [DEBUG] [2014-04-05 23:40:27] [content_data_performance_spec.rb:47:Init one object clone from exist object of 350000 in less thes 300 seconds: finished in 42 seconds]
> [DEBUG] [2014-04-05 23:40:37] [content_data_performance_spec.rb:47:Init more then one object two object of 350000 instances each in less then 600 seconds: finished in 8 seconds]
> [DEBUG] [2014-04-05 23:40:49] [content_data_performance_spec.rb:47:Init more then one object three object of 350000 instances each in less then 900 seconds: finished in 10 seconds]
> [DEBUG] [2014-04-05 23:41:24] [content_data_performance_spec.rb:47:Iteration each instance on 350000 instances in less then 300: finished in 32 seconds]
> [DEBUG] [2014-04-05 23:41:54] [content_data_performance_spec.rb:47:minus of two objects with 350000 instances each finish in less then 300 seconds: finished in 25 seconds]

**Comment by kolmanv** [comment]
I don't understand why your work go to waste? Don't agree I'm using your
benchmark. Why do you say so?

**Comment by bbfsdev** [comment]
I'm having the same results as you are both in add_google_hashes branch and in issue260\* branch. @yarondbb please release Gena branch, i.e., issue260_diff_performance.

**Comment by genadyp** [comment]
#### Intermediate results

Tests ContentData specifications:
basic ContentData methods on 350_000 instances
- finish in less then within 5 minutes
- consume less then 250 MB

---

Was found that ConntentData cloning is extremely expensive operation

> Init one object 350000 instances in less then 300 seconds: finished in **5** seconds
> Init one object clone of 350000 in less then 300 seconds: finished in **59** seconds
> Init more then one object two object of 350000 instances each in less then 600 seconds: finished in 9 seconds
> Init more then one object three object of 350000 instances each in less then 900 seconds: finished in 15 seconds
> Init more then one object three object of 350000 instances each in less then 900 seconds: finished in 15 seconds

then minus of two ContentData objects was re-written without using cloning 

---

Was found that performance of Ruby2.1.1 is much better than Ruby1.9.3

> $ rvm current
> **ruby-1.9.3-p327**
> $ rspec -fd spec/content_data/content_data_performance_spec.rb
> .....
> minus of two objects with 350000 instances each finish in less then 300 seconds: **do not finished in 300 seconds**
> 
> $ rvm current
> ruby-2.1.1
> $ rspec -fd spec/content_data/content_data_performance_spec.rb
> ......
> minus of two objects with 350000 instances each finish in less then 300 seconds: **finished in 25 seconds**

**Then it is highly recommended to move to Ruby2.1.1**
With Ruby1.9.3 we still remain above 10 minutes for minus operation

**Comment by AlexeyNemytov** [comment]
I did not find  2.1.1 version for Windows on net
As I see such build dos not exist for Windows
latest stable version 2.0.0

**Comment by genadyp** [comment]
2 @AlexeyNemytov 
- need to talk with @yarondbb - he is using windows
- we concentrate our development for Linux, than I do not know does it matter to use Ruby1.9.3 or Ruby2.1.1 during development - code should run fast on Linux server.
- try to use [pik](https://github.com/vertiginous/pik) - it is like RVM for Windows

**Comment by AlexeyNemytov** [comment]
@genadyp 
No problem observed on Linux
Just wanted to update version on my home laptop
Did not find 2.1.1 for windows .
