### ISSUE TITLE
Incremental diff implementation

### ISSUE THREAD

**Issue by genadyp** [bbfsdev/bbfs#275]
For more details about incremental diff #270 
#### TODO
- [ ] [ContentDataDb](https://github.com/bbfsdev/bbfs/blob/master/lib/content_server/content_data_db.rb) should be taken into action with a [ContentServer](https://github.com/bbfsdev/bbfs/tree/master/lib/content_server)
- [ ] Use a [ContentDataDb#get](https://github.com/bbfsdev/bbfs/blob/master/lib/content_server/content_data_db.rb#L304) to initialize the system instead of ContentData object stored at [Params['local_content_data_path']](https://github.com/bbfsdev/bbfs/blob/bbfs_release_1_7_2/lib/content_server/server.rb#L12)
- [ ] End-to-end testing
- [ ] _(Optional - need to ask Shiray)_ Add to [file_utils](https://github.com/bbfsdev/bbfs/blob/master/bin/file_utils) a functionality to
  - diff between two timestamps
  - snapshot for the date
- [ ] performance tests for [ContentDataDb](https://github.com/bbfsdev/bbfs/blob/issue270_incremental_diff/lib/content_server/content_data_db.rb)

**Comment by bbfsdev** [comment]
So basically this can already be used, right?
Did you do a pull request? (did you pushed your local branch?)

**Comment by genadyp** [comment]
[Pull Request](https://github.com/bbfsdev/bbfs/pull/273/)

@yarondbb 
@kolmanv 
Review please

---

Basically we can use it after the code review and resolving the three first task from the [TODO list](https://github.com/bbfsdev/bbfs/issues/275#issue-44169919)

**Comment by genadyp** [comment]
[Branch merged](https://github.com/bbfsdev/bbfs/pull/273)
